couch:
  protocol: http
  domain: SERVER_COUCH_DOMAIN
  port: SERVER_COUCH_PORT
token:
  secret: SERVER_SECRET
  iss: SERVER_JWT_ISS
  exp: SERVER_JWT_EXP
server:
  domain: SERVER_DOMAIN
  port: SERVER_PORT
