couch:
  domain: SERVER_COUCH_DOMAIN
  port: SERVER_COUCH_PORT
  username: SERVER_COUCH_USERNAME
  password: SERVER_COUCH_PASSWORD
token:
  secret: SERVER_SECRET
  iss: SERVER_JWT_ISS
server:
  domain: SERVER_DOMAIN
  port: SERVER_PORT
mail:
  send: SERVER_SEND_MAIL
