couch:
  protocol: http
  domain: localhost
  port: 5984
  username: admin
  password: admin
token:
  secret: secret
  iss: bicycletouringcompanion.com
server:
  domain: localhost
  port: 8080
mail:
  account: no-reply@bicycletouringcompanion.com
  send: false
