couch:
  protocol: http
  domain: localhost
  port: 5984
  username: admin
  password: admin
token:
  secret: secret
  iss: adventurecycling.org
  exp: 15m
server:
  domain: localhost
  port: 8080
mail:
  account: bicycle-touring-companion@adventurecycling.org
  send: false
