couch:
  protocol: https
  domain: couch.bicycletouringcompanion.com
  port: 443
  # username: env SERVER_COUCH_USERNAME
  # password: env SERVER_COUCH_PASSWORD
token:
  # secret: env SERVER_SECRET
  iss: bicycletouringcompanion.com
server:
  domain: btc-app-server-1559933658.us-east-1.elb.amazonaws.com
  port: 80
mail:
  send: true
